---
title: "Untitled"
author: "Shinji Koiso"
date: "2024-04-23"
output: html_document
---

```{r}
library(tidyverse)
#package to read stata data .dat?
library(haven)

#identification strategy
#1. use "port_data.dat" and "ports.xlsx" data to identify mapping between port names and order (id)
#2. assuming every dataset has the same order, construct dyad data 
#3. check whether the order is consistent with other datasets
```

```{r}
#1.
library(readxl)
ports = read_excel("../../airline_data/ports.xlsx")
ports_data <- read.table("../../airline_data/original_data/port_data.dat") %>% 
  mutate(id = 1:nrow(.))

id_port_map = ports %>% 
  left_join(
    ports_data %>% 
  mutate(id = 1:nrow(ports_data)) ,by = c("Latitude" = "V1", "Longitude" = "V2")
  ) %>% 
  select(id,Port) %>% 
  drop_na() 


```

```{r}
#2. assuming every dataset has the same order, construct dyad data according the way to make y.csv
## from 
expand_grid(port1 = id_port_map$Port,port2 = id_port_map$Port) %>% 
  distinct() %>% 
  mutate(dyad = paste(port1,port2,sep = "_")) %>% 
  pivot_wider(names_from = port2,values_from = dyad) %>% 
  left_join(id_port_map,by = c("port1" = "Port")) %>% 
  arrange(id) %>% 
  select(-id,-port1) %>% 
  as.matrix() -> id_port_dyad

iport <- 39
iM <- 741  # 39C2 = 741, not 1431 as commented in the C code

# 空の行列を作成
id_port_dyad_long <- matrix(0, nrow = iM, ncol = 1)
# 下三角部分を抽出
ilast <- 0
for (ci in 1:(iport-1)) {
  iinit <- ilast + 1
  ilast <- iinit + iport - ci - 1
  id_port_dyad_long[iinit:ilast, 1] = id_port_dyad[(ci+1):iport, ci]
}

id_port_dyad_long = id_port_dyad_long %>% 
  as_tibble() %>% 
  mutate(id = 1:nrow(.)) %>% 
  select(id,V1) %>% 
  rename(dyad = V1) %>% 
  mutate(port1 = str_sub(dyad,1,regexpr("_",dyad)-1),
         port2 = str_sub(dyad,regexpr("_",dyad)+1,nchar(dyad)))

id_port_dyad_long
write.csv(id_port_dyad_long,"../../airline_data/dyad_output/id_port_dyad_long.csv", row.names=FALSE)

```

```{r}
#3. since ports.xlsx is the only source where names of ports are available, check whether id_port_dyad_long is correct by comparing between Population variable created from ports.xlsx and x.csv
port_pop = ports %>% 
  left_join(
    id_port_map,by = c("Port" = "Port")
  ) %>%
  drop_na(id) %>% 
  select(Port,Population) 

dyad_pop = id_port_dyad_long %>% 
  left_join(
    port_pop,by = c("port1" = "Port")
  ) %>%
  left_join(
    port_pop,by = c("port2" = "Port")
  ) %>% 
  mutate(Population_port_xlsx = Population.x * Population.y /10000000000000) %>% 
  select(dyad,Population_port_xlsx) 

x_ANA = read.csv("../../airline_data/greco/x_ANA.csv")
```


```{r}
dyad_pop %>% 
  bind_cols(x_ANA %>% select(Population) %>% rename(Population_X = Population)) %>% 
  ggplot(aes(x = Population_port_xlsx, y = Population_X)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  labs(title = "Comparison between Population variable created from ports.xlsx and x_ANA.csv",
       x = "Population from ports.xlsx",
       y = "Population from x_ANA.csv")

#save
ggsave("../../airline_data/figures/Population_comparison.png",width = 10,height = 10)
```





